language: python
sudo: false
python:
    - "3.5"

install:
    # Base requirements
#    - conda config --set always_yes yes --set changeps1 no
#    - conda info -a
    - bash install-dependencies.sh -t
    - source activate shakelib2
    # Install shakelib
    - python setup.py install
before_script:
    # This is to take care of Invalid DISPLAY variable
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
script:
    - export PYTHONPATH="."
    - py.test --cov=shakelib

after_success:
    - pip install codecov codacy-coverage
    - codecov
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
